docs: add badges
casdoor/casdoor-java-sdk pull request #12
Opened 2021-10-30 10:27 UTC by seriouszyx

Signed-off-by: “seriouszyx” <seriouszyx@foxmail.com>
#8

2021-10-30 11:09 UTC, hsluoyz requested changes

2021-10-30 11:09 UTC, hsluoyz commented on README.md
> +[![codebeat badge](https://codebeat.co/badges/44f7a8fb-1eca-4590-a1f0-ae13a053857e)](https://codebeat.co/projects/github-com-seriouszyx-casdoor-java-sdk-master)
should be our org here?

2021-10-30 11:09 UTC, hsluoyz commented on README.md
> +[![codecov](https://codecov.io/gh/seriouszyx/casdoor-java-sdk/branch/master/graph/badge.svg?token=5DVSWSOGLQ)](https://codecov.io/gh/seriouszyx/casdoor-java-sdk)
should be our org here?

2021-11-01 04:59 UTC, seriouszyx commented
@hsluoyz Codebeat and Codecov access request for Casdoor Organization has been sent, plz approve.

2021-11-01 05:36 UTC, hsluoyz commented
@seriouszyx approved.

2021-11-01 08:07 UTC, hsluoyz approved these changes

2021-11-01 08:07 UTC, merged