fix CasdoorUser serializable method to ObjectMapper & the entity annotation lose
casdoor/casdoor-java-sdk pull request #32
Opened 2022-09-07 15:14 UTC by Zerek-Cheng

The original BeanUtils.copyProperties copy method cannot deep copy arrays and lists
Now I replace it with using ObjectMapper to deserialize via json payloader

2022-09-07 15:23 UTC, hsluoyz commented
@conghuhu

2022-09-07 15:54 UTC, conghuhu requested changes

2022-09-07 15:54 UTC, conghuhu commented on src/main/java/org/casbin/casdoor/service/CasdoorAuthService.java
> +            mapper.configure(com.fasterxml.jackson.databind.DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
- I think the ObjectMapper should be cached. This way, you don't have to new ObjectMapper() every time.
- Remove unnecessary comments and only keep your code.

2022-09-08 00:34 UTC, conghuhu commented
LGTM

2022-09-08 01:15 UTC, merged