fix: null to empty string
casdoor/casdoor-java-sdk pull request #36
Opened 2022-10-01 08:48 UTC by gtn1024

See: https://github.com/casdoor/casdoor/pull/1172

2022-10-01 12:42 UTC, hsluoyz requested changes

2022-10-01 12:42 UTC, hsluoyz commented on src/main/java/org/casbin/casdoor/entity/CasdoorUser.java
> +    private String github = "";
Can you sync all the fields from Go?

2022-10-02 01:49 UTC, gtn1024 commented on src/main/java/org/casbin/casdoor/entity/CasdoorUser.java
> +    private String github = "";
done

2022-10-02 02:18 UTC, hsluoyz approved these changes

2022-10-02 02:33 UTC, hsluoyz commented
@gtn1024 demo video?

2022-10-02 02:47 UTC, gtn1024 commented
@hsluoyz I used [casdoor-spring-boot-example](https://github.com/casdoor/casdoor-spring-boot-example) with [casdoor-spring-boot-starter](https://github.com/casdoor/casdoor-spring-boot-starter) to test the code, and make some changes in `pom.xml`, seems great.

<img width="580" alt="image" src="https://user-images.githubusercontent.com/69113276/193435598-04aeaa37-3d16-463b-9c93-1755ab6ff5a6.png">

https://user-images.githubusercontent.com/69113276/193435614-8fbd59e2-54af-4aa9-a128-83864abde0d4.mp4

2022-10-02 04:15 UTC, merged