feat: add CasdoorUserService and CasdoorAuthService
casdoor/casdoor-java-sdk pull request #4
Opened 2021-08-15 09:18 UTC by tangyang9464

Signed-off-by: tangyang9464 <tangyang9464@163.com>

refer to: [casdoor-go-sdk](https://github.com/casdoor/casdoor-go-sdk)

2021-08-15 09:43 UTC, hsluoyz requested changes

2021-08-15 09:43 UTC, hsluoyz commented on src/main/java/org/casbin/casdoor/entity/CasdoorUser.java
> +// Copyright 2020 The casbin Authors. All Rights Reserved.
2021

2021-08-15 09:43 UTC, hsluoyz commented on src/main/java/org/casbin/casdoor/config/CasdoorConfig.java
> +package org.casbin.casdoor.config;
license header

2021-08-15 09:43 UTC, hsluoyz commented on src/main/java/org/casbin/casdoor/entity/Organization.java
> +// Copyright 2020 The casbin Authors. All Rights Reserved.
2021

2021-08-15 09:43 UTC, hsluoyz commented on src/main/java/org/casbin/casdoor/util/http/CasdoorResponse.java
> +package org.casbin.casdoor.util.http;
header

2021-08-15 09:43 UTC, hsluoyz commented on src/main/java/org/casbin/casdoor/util/http/HttpClient.java
> +// Copyright 2020 The casbin Authors. All Rights Reserved.
2021

2021-08-17 03:54 UTC, tangyang9464 commented
@hsluoyz changed

2021-08-17 12:31 UTC, hsluoyz commented
@fangzhengjin @Kininaru plz review

2021-08-19 12:06 UTC, merged